/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        darkBg: '#1e1133',
        darkCard: '#0f0c1f',
        lightCard: '#fafafa',
        lightBorder: '#e0e0e0',
        purple: '#a078ff',
        purpleLight: 'rgba(160, 120, 255, 0.08)',
        purpleBorder: 'rgba(160, 120, 255, 0.6)',
        darkText: '#fff',
        lightText: '#111',
        mutedText: 'rgba(255, 255, 255, 0.55)',
        mutedTextLight: '#777',
        red: '#d93636',
        orange: '#d97b1c',
        redError: '#ff5050',
        redBg: '#c0392b',
        greenAccent: '#3cd28a',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        serif: ['Fraunces', 'serif'],
      },
      fontSize: {
        tiny: '7px',
        xs: '9px',
        sm: '11px',
        base: '13px',
        lg: '14px',
        xl: '15px',
        '2xl': '16px',
        '3xl': '17px',
        '4xl': '24px',
        '5xl': '52px',
      },
      spacing: {
        0.25: '1px',
        0.5: '2px',
        0.75: '3px',
        1: '4px',
        1.25: '5px',
        1.5: '6px',
        1.75: '7px',
        2: '8px',
        2.25: '9px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        'tighter': '3px',
        'tight': '7px',
        'normal': '10px',
        'loose': '12px',
      },
      borderRadius: {
        xs: '3px',
        sm: '5px',
        base: '8px',
        lg: '10px',
        xl: '12px',
        full: '100px',
      },
      animation: {
        pulse: 'ldpulse 1.2s ease-in-out infinite',
        pulseSlow: 'ldpulse 2s infinite',
        blob: 'blob 7s infinite',
      },
      keyframes: {
        ldpulse: {
          '0%, 100%': { background: 'rgba(160, 120, 255, 0.2)', transform: 'scale(1)' },
          '50%': { background: '#a078ff', transform: 'scale(1.5)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
